version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: it_asset_postgres
    environment:
      POSTGRES_DB: it_asset_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    build: .
    container_name: it_asset_webapp
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=it_asset_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DOCKER_ENV=true
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: python web_app.py
    restart: unless-stopped

volumes:
  postgres_data:
